README.md

My first pull request. Added Install documentation.

Added Bootstrap and EESSI Overlay config to README

---

README.md

Updated README to explicitly set $EPRREFIX

Fixed  README

---

README.md

Added  instructions to update portage and packages to the README

Added update instructions for Prefix packages and Portage

---

README.md

Also improved the rest of that section a bit.

Describe manual procedure for disabling Python 2.7

---

README.md
ansible/playbooks/README.md
ansible/playbooks/install.yml
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/handlers/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/prefix_configuration.yml

Added a task+setting to the Ansible role, and added a note/link in the README for manually fixing this.

Generate locales for Prefix installation

---

README.md
bootstrap-prefix.sh

Still a draft, as it needs to be tested. Closes #53.

Update bootstrap script and use latest snapshot

---

bootstrap-prefix.sh

See https://gitweb.gentoo.org/repo/proj/prefix.git/commit/?id=0d7f6b6eb00d0f51f35019846b8f79048b30be93

Bump amd64 profile from 17.0 to 17.1

---

README.md
bootstrap-prefix.sh

Testing this with the latest snapshot:
```
env PYTHON_TARGETS="python3_7" SNAPSHOT_URL="http://cvmfs-s0.eessi-hpc.org/snapshots" CUSTOM_SNAPSHOT="portage-20201126.tar.bz2" singularity exec -B /local docker://eessi/bootstrap-prefix:centos8-$(uname -m) ./bootstrap-prefix.sh
```

Update bootstrap script and snapshot

---

.github/workflows/install_compatibility_layer.yml
README.md

Also fixed the url to the license file :-)

Change master to main

---

.github/actions/install_compatibility_layer/entrypoint.sh
ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml

This will add the [Gentoo Science Repository](https://github.com/gentoo/sci), which for instance has lmod.

Support multiple overlays, use eclass-overrides, bump version to 2021.02

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
bootstrap-prefix.sh

Update snapshot and bootstrap script for 2021.02

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/install_prefix.yml

Closes #81.
I've currently set the threshold to 15GB, I think that should be sufficient (?).

Add step for checking available disk space in Prefix installation path

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

Make symlink to host's hosts file

---

.github/actions/install_compatibility_layer/Dockerfile
.github/workflows/install_compatibility_layer.yml

Make sure we stick to versions that work with Ubuntu 16 / Python 3.5.

Fix action for installing compatibility layer

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

Add host symlink for /etc/localtime

---

ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml

Only remove the Gentoo repo dir if its config file was changed

---

ansible/playbooks/roles/compatibility_layer/tasks/prefix_configuration.yml

Add step for setting the most recent GCC version as the default version

---

test/compat_layer.py

fix ReFrame tests: don't access parameter value in class body

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
bootstrap-prefix.sh
install_compatibility_layer.sh

Rerunning/rebuilding this now...

RISC-V compatibility layer 20240307

---

.github/workflows/build-and-publish-bootstrap-container.yml
Dockerfile.bootstrap-prefix-debian-11

Trying to solve https://github.com/EESSI/compatibility-layer/pull/209/#issuecomment-2658633435.

Bump versions of Github Actions for build container workflow
