EESSI/compatibility-layer

bootstrap-prefix.sh

I ran into this issue:
```
Connecting to distfiles.prefix.bitzolder.nl (distfiles.prefix.bitzolder.nl)|80.101.160.106|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-07-02 09:03:30 ERROR 403: Forbidden.
...
!!! downloading http://distfiles.prefix.bitzolder.nl/snapshots/portage-latest.tar.bz2 failed!
```
Using `https://` instead fixes it for me...

use https for distfiles.prefix.bitzolder.nl

---

bootstrap-prefix.sh

Take into account that $SHELL may contain something like '/bin/bash --noprofile --norc'
This is probably worth pushing back upstream...

fix determining shell in bootstrap_startscript

---

README.md

I tried the gentoo prefix and I was only able to make it work on a fresh CentOS 8, when I have installed the `gcc`, `gcc-c++` and `make` packages.

Update the bootstrap requirements

---

playbooks/roles/compatibility-layer/defaults/main.yml
playbooks/roles/compatibility-layer/tasks/install_packages.yml

Use us portage set for installing a stack before installing additional packages.
The set wil be created from https://github.com/EESSI/gentoo-overlay/pull/8

Add package set install

---

snapshots/gentoo-20200826.tar.xz.md5sum
snapshots/portage-20200826.tar.xz.md5sum

Added gentoo snapshots as a base for a more robust 2020.08 installation. See #3

Added gentoo snapshots

---

scripts/prefix-symlink-host-paths.sh

Also see #15. This adds some more symlinks that fix NSS: now LDAP, Centrify, SSSD should work (I only tested LDAP myself).
It also adds a `-f` to the rm command, to prevent ugly errors in case the Prefix installation does not have this file itself yet.

More host symlinks for NSS

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml

Removed the default values from the README, since this gets outdated quickly. They can be easily found in the defaults file.

Disable Python 2 support, use configuration files from overlay

---

singularity-bootstrap-prefix.arm64v8.def

For some reason, arm64v8 also requires `gmp-devel` to be explicitly installed. Otherwise, building gcc fails.

Added a Singularity definition file for arm64v8

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

Also fixes an issue with the item in the `package_sets` list: they have to be quoted to prevent them from being interpreted as numbers. This hasn't caused any issues with previous pilots, but in this case `2020.10` would be converted to `2020.1`...

Update Ansible role defaults for 2020.10 pilot

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

WIP, as I still need to test it, and it depends on PR #57 (or you have to set `eessi_host_arch` manually for now).

Install arch-specific set

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

We're skipping 2020.11, so let's bump to 2020.12 in the playbook...

bump EESSI version to 2020.12 in playbook

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

This was missing from #64, hopefully tests will pass again with this...

bump to Python 3.8 in Gentoo Prefix

---

ansible/playbooks/roles/compatibility_layer/tasks/install_prefix.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml

This checks if `$EPREFIX/startprefix` exists, both before doing the Prefix installation (in this case, the prefix installation step will be skipped), and after doing a Prefix installation (to check if the installation succeeded).
Closes #79.

Add checks for existence of the startprefix script

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml
ansible/playbooks/roles/compatibility_layer/tasks/install_packages.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/prefix_configuration.yml

Fixes https://github.com/EESSI/gentoo-overlay/issues/7.
I've added this as a separate step in `install_packages.yml`, as it requires `noreplace: no`, and I don't want to reinstall our entire set every time we (re)run this playbook. Also setting `oneshot: yes` to prevent `glibc` from being added to the `world` file.
We need another PR in https://github.com/EESSI/gentoo-overlay to remove `glibc` from the set.

Reinstall glibc in playbook

---

.github/workflows/pilot_repo.yml

Bumped version `2021.02` to `2021.03`, (temporarily) disabled `ppc64le`, and updated the CVMFS config package to `latest`.

Update pilot CI

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

`/cvmfs/{{ cvmfs_repository }}/host_injections` is a variable symlink with a structure that can be controlled by a (yet to be created) script.

Make glibc trusted dirs reference a CVMFS variable symlink

---

ansible/playbooks/roles/compatibility_layer/tasks/install_packages.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/set_glibc_trusted_dirs.yml
test/compat_layer.py

Closes #104 by adding some steps to the playbook that create an env file for glibc. This ensures that the `user-defined-trusted-dirs` is also used when glibc gets recompiled later on, e.g. when performing security updates.
As there were quite a few glibc steps in the task `install_packages.yml`, I've moved these to a separate task `set_glibc_trusted_dirs.yml`.

Create glibc env file

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
bootstrap-prefix.sh

This pulls in the latest changes for the bootstrap script, uses a new snapshot, changes the snapshot URL to our S3 bucket, and bumps the versions of Python and our pilot (2021.06).

Updates for pilot 2021.06

---

ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/test.yml
test/compat_layer.py

Tests will fail, first need a PR to fix and bump things for 2021.06 (coming soon...).

Run the ReFrame tests at the end of the playbook

---

ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml

I had added this to the task as an attempt to fix the issue with the outdated awesomebytes container, but it didn't actually work. So, this can be removed again.

Remove step for updating the world set

---

ansible/playbooks/roles/compatibility_layer/tasks/install_prefix.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml

Only noticing that you're accidentally trying to build an `x86_64` compat layer on an `aarch64` build host *after* the Prefix bootstrap is kind of annoying...
Tested, works like a charm.

check target CPU architecture with build host in playbook to build compat layer

---

.github/workflows/pilot_repo.yml

These tests are currently only run for PRs and when a merge is done, but I think it makes sense to also run these daily to act as canary-in-the-coal-mine, especially since they're very lightweight...

run ReFrame tests on pilot repo daily at 14:00 UTC

---

Dockerfile.bootstrap-prefix-centos8

(Temporary?) fix for: https://bugs.gentoo.org/824926
I've also changed the base image, which now just uses the (latest) CentOS 8 instead of pinning it to a specific 8.x version.

Add perl to prefix build container

---

ansible/playbooks/roles/compatibility_layer/tasks/set_glibc_trusted_dirs.yml

Closes #119. It now uses `equery` to find out if `glibc` was installed with our `user-defined-trusted-dirs`, instead of doing a `strings` on `libc.a`. The ReFrame test already used `equery`, see https://github.com/EESSI/compatibility-layer/blob/main/test/compat_layer.py#L219.

Use equery to find out if glibc was compiled with our user-defined-trusted-dirs

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/prefix_configuration.yml

cfr. https://github.com/EESSI/software-layer/issues/151
requires https://github.com/EESSI/gentoo-overlay/pull/72

set GCC 9.4.0 as default compiler for 2021.12 compat layer

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml

cfr. https://github.com/EESSI/software-layer/issues/151
This is a better approach than in #138, since bootstrapping with a new compiler (GCC 11.2) and then "downgrading" to an older one is a recipe for disaster... :)

stick to GCC 9.x for bootstrapping 2021.12 compat layer, by masking more recent GCC versions

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml
ansible/playbooks/roles/compatibility_layer/tasks/install_prefix.yml
bootstrap-prefix.sh

These changes will make the bootstrap script use a prefetched git commit from the Gentoo overlay on GitHub, removing the need to provide a snapshot tarball. This gives us more fine-grained control over what should be used as base for the bootstrap.
Furthermore, it sets `auto-sync = no`, which will basically ignore the `emerge --sync` that the bootstrap usually does. This should make the build much more reproducible. @boegel is this enough to close issue #132?
Finally, it also adds a simple step that removes the contents of `$EPREFIX/var/tmp` after completion of the bootstrap process, i.e. it closes #142.

Use git commit instead of snapshot tarball for bootstrap, disable auto-sync, clean var/tmp

---

ansible/playbooks/roles/compatibility_layer/tasks/install_prefix.yml

This will discard any changes in the gentoo git repo directory when rerunning the playbook, and should prevent issues like:
```
TASK [compatibility_layer : Clone the Gentoo git repository into the overlay directory] *************
fatal: [localhost]: FAILED! => {"before": "7eaa2512d1e6ddb44e3b41bbddf6c74723f234ce", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
```

May the force be with the git clone step

---

bot/build.sh
install_compatibility_layer.sh
scripts/cfg_files.sh
scripts/utils.sh

Adding scripts and improving them.
- `bot/build.sh`:
- use version and repository from `cfg/job.cfg` or default
- added header, author, license
- added assumptions
- added `set -e`
- source the above helper scripts
- read `cfg/job.cfg` file
- set core settings if needed: `HTTP_PROXY`, `HTTPS_PROXY`, `LOCAL_TMP`, `LOAD_MODULES`
- expand variables in `LOCAL_TMP` into `STORAGE`
- load modules
- obtain `cpu_target_arch` from `cfg/job.cfg` setting
- bump `eessi_version` to `2023.04`
- calling `install_compatibility_layer.sh`: remove fixed local container, add storage option
- `install_compatibility_layer.sh`:
- add default version + create job/run-specific `/tmp` + fix id for tgz
- add arguments for resuming, retaining tmp and more verbose output
- extended and reformatted usage information
- …

Add and update scripts

---

ansible/playbooks/README.md
ansible/playbooks/roles/compatibility_layer/defaults/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/main.yml
ansible/playbooks/roles/compatibility_layer/tasks/reprod.yml

This created a `reprod` dir in the root of the prefix installation, containing:
- `packages.txt` -> list of installed packages obtained with `qlist -IRv`
- `bootstrap-prefix.sh` -> copy of the used bootstrap script
- `build.json` -> contains (additional) metadata about the build, e.g.:
```
Apptainer> cat /cvmfs/pilot.eessi-hpc.org/versions/2023.04/compat/linux/x86_64/reprod/build.json
{
"gentoo_git_commit": "29492845e41ea6a0a4a9769c7e0ce287d106079b",
"host_kernel": "4.18.0-425.10.1.el8_7.x86_64",
"host_memory": {
"free": 17278,
"total": 29912,
"used": 12634
},  
"host_mounts": [
{
"block_available": 48574849,
"block_size": 4096,
"block_total": 52425979,
"block_used": 3851130,
"device": "/dev/xvda1",
"fstype": "xfs",
"inode_available": 104345170,
"inode_total": 104857024,
"inode_used": …
```

Add reprod task to Ansible role

---

scripts/update-pkgs-EESSI.IO-2023.06_2023-11-15.sh

This is a bit WIP. So far, the `emerge` commands have been run for `x86_64` only. The update will be repeated using this script. Then also run for `aarch64` (after verifying that the GLSAs are the same for `aarch64`).
<details><summary>glsa-check output</summary>
```
Checking GLSA 202309-14
>>> The following updates will be performed for this GLSA:
>>> Updates that will be performed:
app-arch/libarchive-3.7.1 (vulnerable: app-arch/libarchive-3.6.2-r1)
Checking GLSA 202310-03
>>> The following updates will be performed for this GLSA:
>>> Updates that will be performed:
sys-libs/glibc-2.37-r7 (vulnerable: sys-libs/glibc-2.37-r3)
Checking GLSA 202310-12
>>> The following updates will be performed for this GLSA:
>>> Updates that will be performed:
net-misc/curl-8.3.0-r2 (vulnerable: …
```

script for updating compat layer 2023.06

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
bot/build.sh
bot/check-build.sh
install_compatibility_layer.sh
test/compat_layer.py

- changed repository name to software.eessi.io
- fixed creation of tarball at the end of `bot/build.sh`
- should be improved to handle errors when some tmp directory couldn't be determined
- added `bot/check-build.sh` that prepares `.result` file including a status update for the PR comment
- added a bit more debug output in `install_compatibility_layer.sh`, should help with setting up debug sessions
Did not change CI `pilot_repo.yml` yet.

build compat layer software.eessi.io/2023.06

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml

This should fix the issues with `w` and `who` described in https://gitlab.com/eessi/support/-/issues/32, and also the `last` command.
Without these symlinks:
```
$ source /cvmfs/pilot.eessi-hpc.org/versions/2023.06/init/bash 
[EESSI pilot 2023.06] $ w
14:16:24 up 3 days, 23:32,  0 users,  load average: 0.00, 0.00, 0.00
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
[EESSI pilot 2023.06] $ who
[EESSI pilot 2023.06] $ last
last: cannot open /cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64/var/log/wtmp: No such file or directory
```
With the host symlinks in place (tested in a non-published transaction on the pilot Stratum 0):
```
[EESSI pilot 2023.06] $ w
14:17:34 up 3 days, 23:33,  2 users,  load average: 0.00, 0.00, 0.00
USER     TTY        LOGIN@   IDLE   JCPU   PCPU …
```

Add host symlinks for `/var/log/wtmp` and `/var/run`

---

scripts/update-pkgs-EESSI.IO-2023.06_2024-01-31.sh

This addresses some Gentoo GLSAs and a `openssl` CVE. I'll upload the new tarballs manually.
<details><summary>output of glsa check script</summary>
```
>>> The following updates will be performed for this GLSA:
>>> No upgrade path exists for these packages:
dev-libs/openssl-1.1.1u
Checking GLSA 202401-18
>>> The following updates will be performed for this GLSA:
>>> Updates that will be performed:
sys-libs/zlib-1.3-r2 (vulnerable: sys-libs/zlib-1.2.13-r1)
Checking GLSA 202402-01
>>> The following updates will be performed for this GLSA:
>>> Updates that will be performed:
sys-libs/glibc-2.38-r10 (vulnerable: sys-libs/glibc-2.37-r7)
```
OpenSSL 1.1.x is EOL, and we masked 3.x, which is probably why it doesn't show an upgrade path.
</details>
<details><summary>diff for …

Script for updating `openssl`, `zlib`, `glibc` in `software.eessi.io` version 2023.06

---

Dockerfile.bootstrap-prefix-debian-sid
ansible/playbooks/roles/compatibility_layer/tasks/test.yml
test/compat_layer.py

I ran into an issue with `maturin` not being available as a prebuilt wheel, and building from source requires `rustc`, so this PR adds it to the Debian Sid container.
Furthermore, the path to the CVMFS repo was hardcoded to `/cvmfs/software.eessi.io`, so I've also added some option to override that.
Finally, one step in the test task was missing the `test` tag, which means that the step was skipped if the playbook was run with `-t test`.
These changes allowed me to run the test suite:
```
Perform task: TASK: compatibility_layer : Run ReFrame tests (N)o/(y)es/(c)ontinue: *************************************************************************************************************************
TASK [compatibility_layer : Run ReFrame tests] …
```

Fix ReFrame test step for RISC-V

---

Dockerfile.bootstrap-prefix-debian-sid

This is to get rid of the vulnerable XZ version in our build container.
The existing image has:
```
xz (XZ Utils) 5.6.0
```
The new one will have version `5.6.1+really5.4.5-1`:
```
xz (XZ Utils) 5.4.5
```

Bump build container's base image to Debian Sid 20240330

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
scripts/install-sssd-and-nss-pam-ldapd-EESSI.IO-2023.06_2024-04-15.sh

Required by https://github.com/EESSI/gentoo-overlay/pull/99. Note that it also removes a bunch of host symlinks that are no longer required due to the changes in both PRs.
This solves https://gitlab.com/eessi/support/-/issues/32, as it will make use of the host daemons.

Add USE flags for `nss-pam-ldapd` and `sssd`

---

scripts/install-sssd-and-nss-pam-ldapd-EESSI.IO-2023.06_2024-04-15.sh

There was a stupid mistake in #199, which first reinstalled new packages and then removed symlinks. But those new packages actually provided files that replace the symlinks, so the files themselves got removed again later on :man_facepalming:. I fixed the order in the script, and it now first removes the symlinks.
Fixed it in the repo by manually copying the missing files to the Stratum 0, and adding them in a transaction:
```
[mod] /cvmfs/software.eessi.io/versions
[mod] /cvmfs/software.eessi.io/versions/2023.06
[mod] /cvmfs/software.eessi.io/versions/2023.06/compat
[mod] /cvmfs/software.eessi.io/versions/2023.06/compat/linux
[mod] /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64
[mod] /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib64
[add] …
```

Fix order of commands in installation script for `sssd` and `nss-pam-ldapd`

---

ansible/playbooks/roles/compatibility_layer/defaults/main.yml
bootstrap-prefix.sh
install_compatibility_layer.sh

Based on #202, but with some version bumps.

RISC-V compatibility layer 20240402

---

test/compat_layer.py

- don't parametrize the eessi repo dir variable, as that won't work anyway if the versions/architectures can be parametrized as well (repo has to be fixed in that case)
- drop support for the pilot repo by removing the checks for `latest` and `2021.12`
- remove the host symlinks that we no longer use from the host symlink test

Fix broken ReFrame tests

---

ansible/playbooks/roles/compatibility_layer/tasks/add_overlay.yml
ansible/playbooks/roles/compatibility_layer/templates/overlay.conf.j2

This does the same thing (adding a configuration file to `$EPREFIX/etc/portage/repos.conf/` for every custom overlay) with Ansible, which means we no longer need to rely on running an `eselect repository add` command. Besides making things a bit cleaner, it also has the advantage that we can use specific branches. The latter is useful for testing new compat layer installations: you don't need to merge the new package set first (see https://github.com/EESSI/compatibility-layer/pull/209, which worked without having https://github.com/EESSI/gentoo-overlay/pull/108 merged).

Let Ansible configure custom overlays

---

test/compat_layer.py

Closes #144. Note that we have to skip the test for a new version if we decide to drop `pip` from our compat layer, see  https://github.com/EESSI/gentoo-overlay/issues/83.
As we (most likely) won't have `ld.gold` in future versions, and 2023.06 has both `ld.bfd` and `ld.gold`, I've adapted the corresponding check as a preparation for a new EESSI version.
Tested on the 2023.06 stack:
```
[  PASSED  ] Ran 24/24 test case(s) from 24 check(s) (0 failure(s), 0 skipped, 0 aborted)
[==========] Finished on Mon Jan  6 11:17:56 2025+0100
```

Add ReFrame test that runs `pip check` and modify the `ld.gold` check

---

bot/build.sh
bot/check-build.sh
bot/check-test.sh
bot/test.sh
install_compatibility_layer.sh
test_compatibility_layer.sh

This adds a `bot/test.sh` script that lets the bot run the ReFrame tests on top of a compatibility layer that was just built, and also a `bot/check-test.sh` script that makes it report the test results back to the PR. The latter is just a copy of the one that we already use for the software layer.
To make the testing a bit easier and also allow others to easily run the tests, I've also added a `test_compatibility_layer.sh` script: this script is similar to the existing `install_compatibility_layer.sh` and runs the ReFrame tests with an existing or (temporary) pip-installed ReFrame on top of any compatibility layer that is available.
Finally, it makes a small change to the `bot/build.sh` script as well to fix an issue with the version number being used, in the same way as I'm doing it for …

Add `bot/test.sh` script and a generic `test_compatibility_layer.sh` script
